vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    sirop_images:
      uri_prefix: '%app.path.sirop_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.sirop_images%'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
